import Head from 'next/head';
import Image from 'next/image';
import type { NextPage } from 'next';

const Home = () => {
	return (
		<div className=''>
			<Head>
				<title>NFT Drop</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1 className='text-4xl font-bold text-red-500'>
				Welcome to the GTA NFT Drop
			</h1>
		</div>
	);
};

export default Home;
